
[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "Beam"

[font]
size = 18.0
#use_thin_strokes = true

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "Buttonless"
dynamic_padding = true

[window.padding]
x = 10
y = 5

[general]
live_config_reload = true

# define startup program
[terminal.shell]
program = "/opt/homebrew/bin/tmux" # Adjust path if needed
args = ["new-session", "-A", "-s", "LOCAL"]
